spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
    enabled: true
    drop-first: true